// <auto-generated />
using System;
using Ark.Document.Scan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ark.Document.Scan.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Ark.Document.Scan.Models.ScanJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Brightness")
                        .HasColumnType("REAL");

                    b.Property<double>("Contrast")
                        .HasColumnType("REAL");

                    b.Property<string>("Corners")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilterMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessedImagePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("RotationDegrees")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ShareCreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShareToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasAutoDetected")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShareToken")
                        .IsUnique();

                    b.ToTable("ScanJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
